"""initial schema

Revision ID: 5784ac9a50d2
Revises:
Create Date: 2026-05-27 16:06:43.690022

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5784ac9a50d2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
